name: Deploy to Firebase
"on":
  push:
    branches:
      - main
jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Installing Dependencies
        working-directory: ./website
        run: yarn install
      - name: Build
        working-directory: ./website
        run: yarn build
      - name: Install Firebase Tools
        working-directory: ./website
        run: npm install -g firebase-tools
      - name: Deploying to Firebase
        working-directory: ./website
        run: firebase deploy --token "${{ secrets.FIREBASE_SECRET }}"
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Installing Dependencies
        working-directory: ./api/functions
        run: yarn install
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Deploying to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_SECRET }}"
  test-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Installing Dependencies
        working-directory: ./tests
        run: yarn install
      - name: Test
        working-directory: ./tests
        run: yarn test
